apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: default
  labels:
    app: {{ template "ingest.name" . }}
spec:
  ports:
  - name: tcp-6379-6379
    protocol: TCP
    port: 6379
    targetPort: 6379
  {{- if .Values.redisConfig.external.enabled }}
    nodePort: {{ .Values.redisConfig.external.port }}
  type: NodePort
  externalTrafficPolicy: Local
  {{- end }}
  selector:
    app: {{ template "ingest.name" . }}-redis
    redis-node: "true"
    
